services:
  testfrankenphp:
    build:
      context: .
    entrypoint: php artisan octane:frankenphp
    container_name: test-franken-app
    ports:
      - "8081:8000"
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge