services:
  testfrankenphp:
    build:
      context: .
    entrypoint: php artisan octane:frankenphp
    container_name: test-franken-app
    ports:
      - "8081:8000"
    networks:
      - laravel_network

  db:
    image: mysql:8.0
    container_name: test-franken-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

volumes:
  dbdata:
    driver: local